### ISSUE TITLE
【新功能建议】添加对战功能 JJ长度为负数的时候会提示变成女孩子

### ISSUE THREAD

**Issue by ElaineOwO** [MyWifeAsuna/Fuck-QQGroup-Everyone#2]
RT 变成女孩子以后无法长出JJ 而且增加被透的概率（我是魔鬼  
透到一定剂量的脱氧核糖以后会怀孕生子 之后才能重新长出JJ（

**Comment by MyWifeAsuna** [comment]
> RT 变成女孩子以后无法长出JJ而且增加被透的概率（我是魔鬼 透到一定药剂量的脱氧核糖以后会怀胎子之后才能重新长出JJ

玩的好变态啊...
记录下来，有空会考虑...

**Comment by ElaineOwO** [comment]
> > RT 变成女孩子以后无法长出JJ而且增加被透的概率（我是魔鬼 透到一定药剂量的脱氧核糖以后会怀胎子之后才能重新长出JJ
> 
> 玩的好变态啊... 记录下来，有空会考虑...

hhh我又不是什么魔鬼（
像支持大佬 大佬有爱发电吗 我可以投喂一点大米

**Comment by MyWifeAsuna** [comment]
> > > RT 变成女孩子以后无法长出JJ而且增加被透的概率（我是魔鬼 透到一定药剂量的脱氧核糖以后会怀胎子之后才能重新长出JJ
> > 
> > 
> > 玩的好变态啊... 记录下来，有空会考虑...
> 
> hhh我又不是什么魔鬼（ 像支持大佬 大佬有爱发电吗 我可以投喂一点大米

并没有，暂时没有太多空闲时间。以后有大项目会考虑
